# Theme settings 
primaryColor = '#ec7063'#Blue 
backgroundColor = '#48c9b0'# Cyan 
secondaryBackgroundColor = '#48c9b0' #Sky Blue
textColor = '#ffffff'#White 
font = 'sans-serif, 13'#font size increased to 13
